poki/netlib

README.md
=> Added NPM badge next to the title in the Readme

internal/cloudflare/credentials.go, internal/util/http.go
Calls over the websocket to fetch credentials sometimes hang. This change will add more logging to the fetching of credentials and will improve some of the other error logging as well.
=> Add more logging information around credential fetching

cmd/signaling/main.go, internal/signaling/handler.go, internal/signaling/peer.go, internal/signaling/stores/memory.go
- No need to close the channel, just flush it and let it get collected
- Do ForwardMessage in a goroutine to not block other receivers
- Subscribe doesn't block so don't run it in a goroutine
=> Don't send on a closed channel

example/main.ts, internal/signaling/handler.go
See: https://github.com/nhooyr/websocket/issues/218
=> Workaround Safari Websocket Compression issue

.github/workflows/ci.yaml, Dockerfile, go.mod, go.sum
See: https://go.dev/doc/devel/release#go1.20.minor
=> Update Go and dependencies

features/support/steps/network.ts, features/support/types.ts, lib/credentials.ts
Also make the testsuite consume events when checked.
=> Make credential fetching more robust

internal/signaling/stores/postgres.go
Still spamming our error logs. 😓
=> HOTFIX Mute one more ErrNoRows error that is fine.

internal/signaling/handler.go
Don't pass a context with deadline exceeded to a database function.
Giving it a new timeout is also not going to work, see: https://go.dev/play/p/yQcXgpVyJn3
=> Prevent: failed to record timeout peer

lib/latency.ts, lib/network.ts, lib/peer.ts, lib/signaling.ts, lib/types.ts, package.json, tsconfig.json, yarn.lock
Ignore all internal methods and members.
=> Add typescript defs to package

internal/signaling/stores/postgres.go
Use a slightly different query to work around this.
See: https://chat.openai.com/share/7e23cfa9-7ae9-4d83-bf46-f4ee1f25465f
=> Postgress doesn't support LIMIT in DELETE

lib/legacy.ts, package.json
=> Add legacy browsers target

internal/signaling/handler.go, internal/signaling/peer.go, internal/signaling/timeout_manager.go
We still had 2 lingering lobbies, trying to get that to 0.
=> Don't set lobby on failed reconnect.

.sops.yaml, manifest/secrets.yaml
Yoyo @koenbollen! As part of the offboarding formalities, I'm removing your PGP key from the SOPS file and rotating the data key.
You won't have direct access to the secrets anymore, so if you need to edit them, please ask Casper, Erik or me. 🙂
=> Remove @koenbollen's key and rotate secrets

features/lobbies.feature, internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go
And test to make sure we can filter on this data.
=> Store customData when creating a lobby

features/support/steps/backend.ts, features/support/steps/network.ts, features/support/world.ts, internal/signaling/handler.go, package.json
=> Various minor fixes

internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go
Fix TODO we had for this. Makes HandleCreatePacket easier.
=> Add peer to lobby in CreateLobby

features/lobbies.feature, internal/signaling/stores/postgres.go, migrations/1717766658_meta_customData.down.sql, migrations/1717766658_meta_customData.up.sql, migrations/latest.lock
It's more in line with how we name this in other places.
=> Rename meta to custom_data in our database

.github/dependabot.yml, package.json
The file wasn't in the right directory so it had no effect. 😛 Fixed some mistakes too
=> Fix dependabot

manifest/secrets.yaml
Upgrades the secret to use the API-Token system
=> Sops secret update

cmd/signaling/main.go, internal/cloudflare/credentials.go, internal/cloudflare/types.go, manifest/secrets.yaml
Migrate to the new cloudflare endpoint for generating credentials
=> Migrate to the new Cloudflare endpoint

manifest/deployment.yaml
Quick fixup after we removed some env variables
=> Fixup deploy manifest file

go.mod, go.sum, internal/signaling/handler.go, internal/signaling/peer.go, internal/util/http.go
Switch to the maintained fork of this package.
See: https://coder.com/blog/websocket
=> nhooyr.io/websocket -> github.com/coder/websocket

manifest/ingress.yaml
Something that should have been part of #182 that I forgot. So, cleaning up this unnecessary resource 🧹
=> Remove managedCertificate

.github/workflows/build.yaml, go.mod, internal/metrics/client.go, internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/util/http.go
Changes after running
```
go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...
```
Plus changing Go 1.23 to 1.24 in the last places.
=> go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest

internal/signaling/stores/postgres.go
When a `description` packet is received receipient is passed as argument to Publish. This field is not validated and could contain SQL injections. We could validate the field, but a vunerability like this could happen again in the future, therefor it's better to validate the topic in Publish itself.
See: https://github.com/poki/netlib/blob/0dbfcd849e81458205d0bf198e3b03d2cee501ba/internal/signaling/peer.go#L166
This issue was found by OpenAI o3.
=> Prevent sql injection from string concatenation

docs/api-reference.md, docs/basic-usage.md
=> Change disconnect() to close() in documentation
