README.md
NPM can't deal with relative urls, so make it absolute.
=> Fix logo url to work on npm

.github/workflows/ci.yaml, features/support/types.ts, features/support/world.ts, internal/signaling/peer.go, internal/signaling/timeout_manager.go, internal/signaling/types.go, internal/util/identifiers.go, lib/signaling.ts, lib/types.ts
Currently anyone can reconnect as another peer ID and take over the connection. This PR adds a secret so only the original peer can reconnect.
This change is **not** backwards compatible. Games using an old netlib (after this PR) won't be able to reconnect.
=> Send peers a secret to validate reconnects.

example/main.ts, features/basic.feature, features/support/steps/network.ts, internal/signaling/peer.go, internal/signaling/types.go, internal/util/identifiers.go, lib/network.ts, lib/types.ts
Some games want the lobby code to be short so they can be copied verbally and typed in.
This change introduce the codeFormat setting to pick the short lobby code.
Also fixed settings in the create packet.
=> Introduce the sort, typable lobby code

.github/workflows/ci.yaml
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Upgrade to actions/checkout@v3

internal/signaling/stores/postgres.go, internal/signaling/timeout_manager.go
Also I found while testing, the timeout manager should not timeout if the peer has no ID yet.
=> HOTFIX NoRows is not an error.

internal/signaling/handler.go, internal/signaling/peer.go, internal/signaling/types.go, lib/network.ts, lib/types.ts
There was a 'leave' packet that was interpreted differently by the client and server and we corrected this.
Also don't accept any messages anymore after a close message is received.
And when a client closes we don't add them to the timeout manager when the connection is broken.
(leaving of lobbies, as the leave packet was interpreted by the server was never a feature, soon™)
=> Better handle closing of clients

internal/signaling/peer.go
We forgot for a second that we need to be backwards compatible. 🙈 Luckly this was only on closing the connection/client so gameplay wasn't affected.
=> Make the closing of connection backwards compatible.

internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go
We are getting some weird errors in our database that are exceeding the type length. This should help us learn more about the issue.
=> Add len checks for lobby and peer ids

internal/signaling/peer.go, internal/signaling/stores/postgres.go
=> Also check lobbies length in TimeoutPeer store method.

cmd/signaling/main.go, internal/signaling.go, internal/signaling/handler.go
When our backend needs to restart peers are disconnected can could get into the timeouts table, therefor they could reconnect. This PR will make sure all connections are closed when the server shuts down allowing peers to be timed out and reconnect later.
=> Timeout peers when the server is shutdown.

internal/signaling/handler.go, internal/signaling/types.go, lib/signaling.ts, lib/types.ts
Sometimes socket are not closed neatly and the connection to a (in-between) load balancer can be kept open. This pinging should trigger the TCP protocol to disconnect.
=> Ping the websocket every 30 second disconencts are noticed.

internal/signaling/handler.go
ErrorAndDisconnect can only be called in a handler as it panics with http.ErrAbortHandler which normally gets recovered by net/http.
=> Don't call ErrorAndDisconnect in a goroutine

internal/signaling/handler.go, internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go, internal/signaling/timeout_manager.go, internal/signaling/types.go, lib/signaling.ts, lib/types.ts
This changes the rejoining logic. Before the lobby a peer got rejoined to was reported by the client. Now this lobby is returned by the timeout state in the database.
We are making improvements on the reconnecting and on how timed-out peers are handled in order to create a clean lobby list in the database. This is required for implementing features like lobby filtering (for #48 and #49).
=> Rejoin peers into lobbies based on timeoutmanager

internal/signaling/handler.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go
Currently all lobbies stay in the database even if they are empty. This change introduces a simple timer that deletes day old empty lobbies every 30 minutes.
This is needed for better lobby listing (filters, private etc) in the future.
Also snuck in the disabling of websocket compression, see https://github.com/nhooyr/websocket/issues/218#issuecomment-1738672008
=> Clean empty, day old, lobbies on a 30min timer.

features/lobbies.feature, features/support/steps/network.ts, internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go
Previously the `public` setting was ignored by the backend and never saved in the database, thus all lobbies where public and listing lobbies would return everything.
This change actually stored the public setting in the database, the filter for public-only lobbies in listing was already in place.
This is a backwards-incompatible change, but no live games we know of use this feature at the moment.
Fixes #49
=> Set public setting when creating lobby.

internal/signaling/peer.go
When no lobbies are available for a game when listing lobbies the API used to return `null`, this change makes that an empty array instead `[]`.
Fixes #68
=> Listing no lobbies should return an empty array.

internal/signaling/handler.go, internal/signaling/types.go
Client expects credentials to be returned as a promise, but it can't match the response to the request due to response ID not being set:
```typescript
if (packet.rid !== undefined) { // this is always false
const request = this.requests.get(packet.rid)
if (request != null) {
this.requests.delete(packet.rid)
if (packet.type === 'error') {
request.reject(new SignalingError('server-error', packet.message))
} else {
request.resolve(packet)
}
}
}
```
This causes TURN to be completely broken since no credentials are available.
Tested locally by hardcoding some creds:
```go
func (c *CredentialsClient) GetCredentials(ctx context.Context) (*Credentials, error) {
return &Credentials{
URL:        "someURL",
Username:   "bsusername",
Credential: "bspassword",
Lifetime:   123,
}, nil
}
```
Happy to …
=> Fix credentials not being returned along with the request ID

internal/signaling/stores/postgres.go
Thanks to @Pedr0Rocha for spotting this.
=> Return correct error when lobby already exists

features/lobbies.feature, internal/signaling/stores/postgres.go
ARRAY_LENGTH returns NULL instead of 0 for an empty lobby which then can't be scanned into an int.
Fixes https://github.com/poki/netlib/issues/82
=> Fix error on listing empty lobbies

example/index.html, example/main.ts, features/custom-data.feature, features/lobbies.feature, features/support/steps/network.ts, features/support/types.ts, internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go, internal/signaling/types.go, lib/network.ts, lib/signaling.ts, lib/types.ts
The argument to `Network.list` is now an object instead of a string. `Network.join` now resolves to an object containing information about the lobby.
=> Return lobby information when joining a lobby

internal/signaling/peer.go, internal/util/http.go, lib/signaling.ts
Right now clients get stuck in a reconnect loop when their secret is bad. This change makes it so they don't immediately reconnect. WebRTC connections will stay in tact, so players will be able to keep playing. But they won't be able to list or join other lobbies without reloading the game.
=> Fix reconnect loop when reconnecting with bad secret

internal/signaling/handler.go
Seeing this when debugging failing tests once in a while. Can be safely ignored.
=> Also ignore lingering disconnected packet

internal/metrics/client.go, internal/signaling/handler.go, internal/signaling/stores/postgres.go, internal/util/time.go
Otherwise there are issues when running the test locally on a machine that isn't in UTC. CURRENT_TIMESTAMP in the postgress container will return a time in UTC, but time.Now() will return it in the local time which messes up the TimeoutManager.
I found this when running tests with the TimeoutManager, and noticed it was timing out peers immediately instead of after the minute that is configured.
Since we can't test the database in tests we can't write a feature test for this yet. We'll have to write this after https://github.com/poki/netlib/issues/65
=> Always work with UTC time

features/support/steps/network.ts, features/support/world.ts
Give the Network a little bit of time to connect to the signalling backend before we continue with the next step. This makes our tests less flaky. Found out when some lobby tests where we create multiple players after each other was failing because their ID was changing (as they are given out in order).
=> Make createPlayer have a small delay

features/support/steps/network.ts
Inserting `[]` into postgress will give an error that it doesn't know the type of the array. Since we're always inserting arrays of strings here we can specify the type here.
Also converts `null` to insert `NULL` instead of the string `'NULL'`.
These are currently no in use, and because of that changes to the tests aren't needed. But I want to introduce tests with these in the Lobby Leader pull, and want to keep that pull simple and small.
=> Fix test data empty array and NULL value inserts

lib/signaling.ts
If we reconnect too quickly, the signalling server won't have the time to add our information to the database yet and the reconnect won't recognize us. This can be fixed by waiting a little bit before we reconnect.
When we only disconnect for shortly it will take the signaling server longer to notice the disconnect than to reconnect. In which case the reconnect isn't recognized as a disconnect.
This is still not a perfect solution and best-effort only. But from my testing where I noticed this happening it was fixed this way for now.
=> Fix reconnects not being recognized

internal/signaling/peer.go
This code was added 2 years ago together with the TimeoutManager. It is currently impossible to leave a lobby while being disconnected, so the code isn't needed anymore. This code was probably only for backwards compatibility with existing lobbies when it was deployed.
=> Remove code for fakeJoinPacket on reconnect

features/basic.feature, internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go, internal/signaling/timeout_manager.go
Instead of always getting a list of peers and pushing a message to each of then, we Subscribe on a lobby topic as well so we can publish on that.
=> Have a topic per lobby

features/basic.feature, features/custom-data.feature, features/lobbies.feature, features/reconnect.feature, features/support/steps/network.ts
Implicitly show the player ID in the test step. Makes it easier to read the tests.
Also add a `Given "..." are joined in a lobby for game "..."` step that simplifies test setup.
=> Given "..." is connected as "..." and ready for game "..."

internal/signaling/peer.go
This bug was introduced with the rebasing of the previous pull requests.
=> Don't connect to yourself

.build/dependabot.yml
Group updates of packages per ecosystem instead of single pull requests per dependency.
For example:
=> Make dependabot group updates in a single pull weekly

internal/signaling/stores/setup.go
When just running 'go run cmd/signaling/main.go' for local testing you don't want the database to expire.
=> Only expire the temporary postgres in tests

internal/signaling/peer.go, internal/signaling/stores/postgres.go, internal/signaling/stores/shared.go
This gets triggered by developers building their game and trying things. No need to log it as an error. Also add the reason why the update was not allowed so we can see what is happening most.
=> Make "failed to update lobby" a warning, and add information

internal/signaling/handler.go, internal/signaling/peer.go, internal/util/http.go
And also ignore net.ErrClosed (use of closed network connection), which started happening after the last websocket update, which changed how closing of websockets is done.
See: https://github.com/nhooyr/websocket/releases/tag/v1.8.11
=> Rename IsPipeError to ShouldIgnoreNetworkError

features/support/steps/network.ts, features/support/types.ts, features/support/world.ts, lib/index.ts, lib/network.ts, lib/peer.ts, lib/signaling.ts, lib/types.ts, package.json, yarn.lock
We need to keep node-fetch at 2.x.x, 3.x.x is not compatible with cucumber.
=> Update ts dependencies

cmd/signaling/main.go, internal/util/http.go, internal/util/http_test.go
I want to proxy this service behind Cloudflare in order to hide its IP. Cloudflare has its own rules for what to cache and how long. I don't want to rely on that, this force it to never cache.
=> Add Cache-Control: no-store

internal/util/http.go
Seeing this error a lot. It's nested in such a way that we can't seem to Unwrap it, so do string matching.
=> Ignore broken pipe

internal/util/http.go
The other attempt did not work as the broken pipe error might have been too nested. With this change we try to catch it at the top-level.
=> Ignore broken pipe v2

internal/signaling/handler.go, internal/util/http.go
There is something strange causing these errors which also prevents people from joining lobbies. Log the errors as warnings so we can at least investigate them, but they won't show up in Poki's error logging tools.
=> Log broken pipe errors as warnings

manifest/deployment.yaml, manifest/ingress.yaml, manifest/kustomization.yaml, manifest/rbac.yaml, manifest/ssl-certificate.yaml
We put the ingress behind cloudflare. Cloudflare will intercept requests and prevent Google's domain validation protocol from working. We set up cert-manager to get around this problem.
Don't forget to apply the RBAC before merging! ⚠️
=> Replace ManagedCertificate with Certificate

features/leader.feature, features/support/world.ts
This apparently happens a lot in our CI. We had it exit with status code 0 instead of when a step actually failed.
See for example: https://github.com/poki/netlib/actions/runs/12979606225/job/36195532784#step:6:100
=> Fix the exit code in case of 'cucumber did not exit cleanly'

features/basic.feature, features/custom-data.feature, features/leader.feature, features/lobbies.feature, features/maxPlayers.feature, features/password.feature, features/reconnect.feature, internal/util/identifiers.go, lib/latency.ts
Tests were using identifiers generated with a globally seeded `rand.Intn` etc. Working on some changes I found out that `pgx` also uses the global rand internally. Adding an extra query somewhere would make some tests have different identifiers all of a sudden.
Use a local statically seeded random number generator for tests so identifiers really always are the same.
=> Make tests deterministic

features/support/steps/network.ts
Otherwise you'll get an unclear UnhandledPromiseRejection instead of a proper error message.
For example when a `"peer" connects to the lobby` step is done with the wrong lobby you would get a:
```
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "[object Object]".
at throwUnhandledRejectionsMode (node:internal/process/promises:392:7)
at processPromiseRejections (node:internal/process/promises:475:17)
at processTicksAndRejections (node:internal/process/task_queues:106:32)
```
After this change you get:
```
SignalingError {
type: 'server-error',
message: 'lobby not found',
event: undefined,
code: 'lobby-not-found'
}
```
=> Cucumber steps calling async functions should await them

Dockerfile, cmd/signaling/main.go, cmd/testproxy/main.go, internal/cloudflare/credentials.go, internal/signaling/peer.go, internal/signaling/stores/shared.go
I used the following command to concatenate everything into one big blob:
```sh
npx repomix --ignore ".github/,.parcel-cache/,dist/,docs/,node_modules/,TODO.md,yarn.lock,LISENCE,features/,.dockerignore,.gitignore"
```
Then I pasted it into various LLMs with this prompt:
```
Find any potential bugs or issues in this code:
<big blob here>
```
OpenAI O1: https://chatgpt.com/share/67a2f13f-eed4-8000-a7c5-2b3194a6bd42
Google Gemini: https://gist.github.com/erikdubbelboer/529ba1ab62e7c9603a84b454be595da9
DeepSeek R1: https://gist.github.com/erikdubbelboer/9487f4262a6aae9bcc3ae765b3e7d8b6
The prompt was too big for Claude 3.5 Sonnet.
Most "bugs" or issues it find are either wrong or irrelevant. For example any concurrency or security issue in testproxy. Some things are even wrong such as Gemini …
=> Fix minor issues found by LLMs

internal/signaling/handler.go
There is no need to always disconnect the Websocket connection after an hour. This just causes issues once in a while with db queries being executed at the same time and then being cancelled.
**Edit:** it's actually causing issues quite often with`MarkPeerAsActive`. This function is scheduled every 30 seconds with a ticker. Because it's a ticker and keeps rhythm perfectly it is always running right after the hour and almost always causes a failed with `context deadline exceeded` error.
=> Remove peer MaxConnectionTime

internal/signaling/handler.go, internal/signaling/peer.go, lib/signaling.ts
Send pings to be able to detect broken connections. No need for a pong, TCP will take care of that.
Log the origin with "unknown packet type received" so we can see which clients are sending packets the server doesn't support (in this case it was ping from old clients?).
Fixes https://github.com/poki/netlib/issues/183
=> Ping the signaling server from the client

internal/signaling/handler.go
These are network errors we just don't want to log. They will still cause the connection to be closed and the context to be cancelled causing MarkPeerAsActive to error with 'context canceled'.
=> Don't call MarkPeerAsActive when util.ShouldIgnoreNetworkError is true

internal/signaling/timeout_manager.go
It just means the connection was closed the same time we tried to mark the peer as active.
=> Ignore context.Canceled errors when marking a peer as active

lib/signaling.ts
If we don't return after the reject we would still try to send the message.
This issue was found by OpenAI o3.
=> Don't try to send a message on a closed websocket connection

internal/signaling/stores/postgres.go
Right now the secret is ignored as we don't check if any actual rows have been updated (with the `WHERE secret = ?`).
I tried writing a test for this but we don't have an easy way to change the secret during a test.
This issue was found by OpenAI o3.
=> Validate the reconnect secret

lib/index.ts
It's currently required to set `NODE_ENV=production` while building your app. This is very unintuitive. Default to using the production server instead of a local test server.
Fixes: https://github.com/poki/netlib/issues/250
=> Default the signalling server to production

README.md, cmd/signaling/main.go, internal/signaling/stores/postgres.go, internal/signaling/stores/setup.go
- Add better explanation on how to run the signaling server yourself.
- Improve temporary postgres setup.
Also cleanup the error when the store can't be setup. Otherwise you get this confusing broken stacktrace:
```
% docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 netlib 
2025-07-22T09:52:33.883Z	INFO	signaling/main.go:29	init	{"env": "local", "service": "netlib", "component": "signaling"}
2025-07-22T09:52:33.990Z	INFO	stores/setup.go:77	using database	{"env": "local", "service": "netlib", "component": "signaling", "url": "postgres://test:test@localhost:33225/test?sslmode=disable"}
2025-07-22T09:54:32.873Z	PANIC	signaling/main.go:35	failed setup store	{"env": "local", "service": "netlib", "component": "signaling", "error": "reached retry deadline: failed to …
```
=> Improve Docker setup

internal/metrics/client.go
- Change our events client timeout from 5s to 10s
- Each retry now uses a new timeout context instead of one for all of the them
=> Increase events timeout to 10s, use one timeout per retry

internal/signaling/handler.go
This will allow us to detect disconnects much earlier. Ping packets are very light and don't use a lot of bandwidth.
=> Lower the websocket ping interval from 30 to 2 seconds

.github/dependabot.yml
Wait 5 days to get updates. We hope supply chain attacks are detected before these 5 days.
=> Delay dependabot updates by 5 days
